[platformio]
default_envs = seeed_xiao_esp32c3

[env]
framework = arduino
monitor_speed = 115200
build_flags =
    !echo '-DBUILD_GIT_BRANCH=\"'$(git rev-parse --abbrev-ref HEAD)'\"'
    !echo '-DBUILD_GIT_SHA=\"'$(git rev-parse --short HEAD)'\"'
extra_scripts = pre:scripts/generate_settings_header.py
lib_deps =
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.4.2

[env:seeed_xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
